### ISSUE TITLE
Restart Button

### ISSUE THREAD

**Issue by DeeKahy** [Lodestone-Team/lodestone#104]
This feature would be beneficial for users who frequently need to restart the system, such as for troubleshooting or updating purposes.

**Comment by Ynng** [comment]
@CheatCod this might require changes in lodestone core.

As in, the core should be responsible for re-launching the instance after the "shutdown" part of restart. There should be a new action end point specifically for restarting.

The user might close/leave dashboard immediately after clicking restart.

**Comment by Ynng** [comment]
Lodestone core changes should be done, just need frontend now
