### ISSUE TITLE
Better first-time setup page

### ISSUE THREAD

**Issue by Ynng** [Lodestone-Team/lodestone#106]
Redesign is needed for the first time setup page, and the "setup new core" page.

More information should also be provided to guide the user
![image](https://user-images.githubusercontent.com/44907675/212566739-60854cd9-2380-48a5-8569-888d71f264e1.png)

**Comment by Ynng** [comment]
Preview of new design
![image](https://user-images.githubusercontent.com/44907675/212571151-245f253b-d85b-47ee-9471-eb81572de01d.png)

**Comment by Arcslogger** [comment]
figma done

https://www.figma.com/file/MLYjWHZBuPO3pd3aSY39jM/Landing-Page-(new)?node-id=104%3A645&t=UskpqSTGmAfDk0j2-1
