### ISSUE TITLE
Update to MinecraftFlavour and MinecraftSetupConfigPrimitive

### ISSUE THREAD

**Issue by jasonw930** [Lodestone-Team/lodestone#139]
MinecraftFlavour and MinecraftSetupConfigPrimitive have been updated to store version info for flavours.

MinecraftFlavour can be a string or an object, the objects have additional version info
MinecraftSetupConfigPrimitive has fabric version fields removed

Calls to get the Minecraft versions need to ensure that a string flavour name is passed in the URL, not the entire object
Calls to create a Minecraft instance need to ensure that the new flavour data type is passed correctly

**Comment by jasonw930** [comment]
See https://github.com/Lodestone-Team/lodestone_core/tree/dev/forge-support/bindings

**Comment by Ynng** [comment]
Should be done
