### ISSUE TITLE
Make the player list component for minecraft

### ISSUE THREAD

**Issue by Ynng** [Lodestone-Team/lodestone#145]
Make a component that given a list of minecraft user names, display a list of minecraft pfps with the respective usernames. See https://www.figma.com/file/GHwQ9J4tZSYHtGBuS3ZFAZ/final-wireframes?node-id=2795%3A23913&t=l76Qo1XHYFTDZXAI-0

![Image](https://user-images.githubusercontent.com/44907675/220241548-2126a9ed-9809-4064-9577-23eda12cb7de.png)

**Comment by kevinzhangTT** [comment]
https://github.com/Lodestone-Team/lodestone/pull/176
