### ISSUE TITLE
Give some time between when core stops responding and the "Core Connection Error" pops up

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/lodestone#153]
Currently, the Core Connection Error pops up almost immediately when the core stops responding to the WS ping, which is a bit jarring. Let's give it more buffer time to attempt to reconnect before the pop-up. 

![image](https://user-images.githubusercontent.com/47200772/219291700-01e3651f-6971-4cd5-ac0f-e396589209df.png)

**Comment by Ynng** [comment]
Also that button looks a bit wack

**Comment by Ynng** [comment]
fixe in cf3dccbc795d7677c27db58f8cc84119e4820db7
