### ISSUE TITLE
Unify error graphics

### ISSUE THREAD

**Issue by Ynng** [Lodestone-Team/lodestone#157]
Some examples of what I'm talking about

![Image](https://user-images.githubusercontent.com/44907675/219880844-fd97ded4-afd8-4d5d-b245-8607ec1fbdbf.png)
![Image](https://user-images.githubusercontent.com/44907675/219880845-0dc33ef2-95ce-409b-ba37-a3b8ba164b70.png)

Currently these errors are hard coded wherever they are needed.
We should unify them and make it one component instead.
Call it `ErrorGraphics` or `WarningIllustration` or whatever is fitting.

You can easily find existing hard-coded implementations of these by searching for `<FontAwesomeIcon` globally in vscode

**Comment by Arcslogger** [comment]
make sure ur linking PRs to issues!
