### ISSUE TITLE
Deletion of instance should check whether instance is running

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/lodestone#172]
Current behaviour: If an instance is in a non-stopped state, clicking deleting will result in a toast telling the user the instance cannot be deleted while running.

Improved behaviour: Forbids the user from requesting delete on a non-stopped instance

**Comment by CheatCod** [comment]
@NicholasLin718 make the delete button noninteractive with a tooltip saying one should stop the instance first if the instance is running

**Comment by NicholasLin718** [comment]
Tooltip won't work on disabled-buttons. Keep current behavior.
