### ISSUE TITLE
ARM64 package?

### ISSUE THREAD

**Issue by glenskie16** [Lodestone-Team/lodestone#188]
Just wondering if an arm package will be available

**Comment by CheatCod** [comment]
It would be, but it will also mean another build for CI, and we aren't sure if we have enough limit for that..

**Comment by glenskie16** [comment]
how would i do it locally i guess? cause i use ARM processors for all my stuff haha

**Comment by CheatCod** [comment]
If you setup npm and the Rust tool chain then you can compile it locally yourself

**Comment by ekwoka** [comment]
arm for windows? linux?

the MacOS one should already have inside of it both ARM and Intel bindings.

**Comment by CheatCod** [comment]
Actually soon enough we will have an arm release for lodestone_core (alongside with docker support)

**Comment by Ynng** [comment]
arm 64 is now supported with lodestone cli
https://github.com/Lodestone-Team/lodestone_cli/releases/tag/v1.0.0
