### ISSUE TITLE
Add an indicator that a progression event has started

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/lodestone#207]
Currently there is no indicator for the start of a file upload, instance setup etc. Maybe a animation / notification dot on the notification icon would be nice

**Comment by CheatCod** [comment]
Add a progress circle similar to ubuntu gnome DE

**Comment by Ynng** [comment]
also can you pls make the red dot clickable (or make the mouse click through it)

![Image](https://github.com/Lodestone-Team/lodestone/assets/44907675/85068d51-c4ce-4c5b-84dd-1bca303fdb49)
