### ISSUE TITLE
Debug option has no description

### ISSUE THREAD

**Issue by kaytitulaer3820** [Lodestone-Team/lodestone#236]
i got this when i looked trough the settings of my paper server.
```
Debug
Unknown property: debug = false. Please report this to the developers.
```
![Screenshot 2023-05-05 100714](https://user-images.githubusercontent.com/76474615/236407075-f0da667f-dc34-43f1-8bf4-7f129883a80e.png)

**Comment by CheatCod** [comment]
Lodestone keeps track of a series of key value pairs of server properties key string which is hard coded to the 1.19 vanilla server. When a string that can't be matched against any of the keys appears it defaults to this message as a description.

This is perfectly harmless and you can still edit the field freely. A better system may be implemented in the future

**Comment by kaytitulaer3820** [comment]
alr thanks for the clarification
