### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by ngregrichardson** [Lodestone-Team/lodestone#259]
I know that in another issue, adding a build for ARM64 was mentioned, where the response was not enough CI support, but I was wondering if having a Docker image for the web app would have the same restriction and, if so, if at least a Dockerfile would be able to be added to easily self-host the app with a single command.

**Comment by CheatCod** [comment]
If I'm understanding correctly you would like a docker image for our dashboard? If so it's pretty doable

**Comment by ngregrichardson** [comment]
Yeah, I had a few minutes free earlier this week and made a Dockerfile but it's hitting issues running `npm install` and I haven't found the time to look at it again.

**Comment by Ynng** [comment]
We have a dockerfile for dashboard now, but I think this is closer to what you are looking for

https://github.com/Lodestone-Team/lodestone_core/pkgs/container/lodestone_core
