### ISSUE TITLE
Add guide on how to add ssl/https certificates

### ISSUE THREAD

**Issue by KaninchenSpeed** [Lodestone-Team/lodestone#263]
Please add a guide on how to add ssl/https certificates.

**Comment by Ynng** [comment]
Does backend generate ssl/https certificate or does the user need to do it themselves?
@CheatCod

**Comment by KaninchenSpeed** [comment]
@Ynng No, I couldn't find a way to do this. I just symlinked the cert files from certbot.

**Comment by CheatCod** [comment]
Create a folder called `tls` under `LODESTONE_PATH`, and put in `cert.pem` and `key.pem`

**Comment by a-almallah** [comment]
I generated cert.pem and key.pem under tls in the lodestone folder. but it still outputs.

` WARN Invalid TLS config : No such file or directory (os error 2), using HTTP`

**Comment by Ynng** [comment]
I've added the same info to our wiki page https://github.com/Lodestone-Team/lodestone/wiki/How-Tos#configuring-sslhttps-with-lodestone-core
