### ISSUE TITLE
Thank you pop up for prerelease version

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/lodestone#272]
If either the dashboard or core is using beta or alpha version of lodestone, for ex. v0.5.0-beta.1, then do a pop up to

1. Thank the user for testing
2. Indicate risk of beta testing

Store the last version in local storage, and pop up when the current version is later than last version, or if last version is not in local storage

**Comment by Ynng** [comment]
It should pop up once per version

**Comment by CheatCod** [comment]
ETA: 1 week
