### ISSUE TITLE
Can't stop or restart an instance that is not running (desktop, browser)

### ISSUE THREAD

**Issue by vadim-a-yegorov** [Lodestone-Team/lodestone#285]
# Description

When the server status sync is lagging and GUI is not showing the right server status, "Stop" and "Restart" buttons don't work. To overcome this user has to close lodestone GUI and reopen it.

# Details

Server status in GUI is wrong:
<img width="967" alt="Screen Shot 2023-07-05 at 9 27 30 PM" src="https://github.com/Lodestone-Team/lodestone/assets/121871103/9f615e32-ee81-44a4-9d5a-8ec0af1cc5a4">

Not able to stop, start or restart the server, no one button works until GUI restart:
<img width="828" alt="Screen Shot 2023-07-05 at 9 27 40 PM" src="https://github.com/Lodestone-Team/lodestone/assets/121871103/65bf54c4-6b80-47d6-b376-379c9e9b8bf6">

# How to solve

- [ ] Add error handling on "Restart" button to make it restart the server when it's running or start the server when it's not

**Comment by vadim-a-yegorov** [comment]
This issues are related to each other: #284, #286, #287

**Comment by vadim-a-yegorov** [comment]
This issue occurs both on:
* Electron (macOS Monterey 12.3.1 tested)
* Browser (Google Chrome Version 114.0.5735.198 (Official Build) (x86_64) tested)

**Comment by Ynng** [comment]
This should be fixed by a more robust status sync system #284

**Comment by vadim-a-yegorov** [comment]
> A more resilient status synchronization system ... should ideally address this issue

@Ynng Yes and no. "Restart" button still should be able to start the server when it's not running instead of displaying error message.
