### ISSUE TITLE
Unable to Join Server after Instance Started

### ISSUE THREAD

**Issue by Type-32** [Lodestone-Team/lodestone#297]
I deployed the lodestone core using docker with untouched config and started one instance running my server on port 25565.
my server ip is [mydomain]:25565, which should be okay. My domain is linked via https protocol through my nginx proxy manager on native lodestone port [myip]:16662. However I cannot join my minecraft server instance through the given server ip ([mydomain]:25565)

**Comment by CheatCod** [comment]
Lodestone does not do any special network stuff, if your server is running normally then it's most likely something to do with your nginx setup, Check that port is available with firework and router

**Comment by Ynng** [comment]
If you meant the "public domain/ip" setting in core settings on the dashboard, that is purely visual.

**Comment by Type-32** [comment]
I'm getting a bit confused here:
my nginx should be redirecting my address ( [address] -> [host domain]:16662 ) correctly and I've checked multiple times before.
my confusion is about the MC server ip address, if I configured it to be at my [address]:25565, wouldn't that be like [host domain]:16662:25565 ? I only know how to open ports on my [host domain]:[port] instead of [host domain]:[port]:[port].

**Comment by Type-32** [comment]
Ok so now I removed my nginx setup and just straight up using my host server's ip for the mc server's ip ( [host server ip]:25565 ). (the public domain/ip settings is set to my host server's ip as well) Now I just can't join the server through my mc server ip and I've already allowed the 25565 port to pass through connections (TCP protocol), in which it just says "Connection Refused" and it couldn't be pinged.

**Comment by CheatCod** [comment]
Did you port forward it on your router? You can look into playit.gg or ngrok

**Comment by Type-32** [comment]
I'm not using my local computer but instead using a server instance I bought online (tencent cloud lighthouse server), so I don't know how to port forward that ip. (the ip is already publicly accessible)

**Comment by CheatCod** [comment]
The IP may be accessible but you'll need to make sure 25565 is accessible

**Comment by CheatCod** [comment]
I can't help you with port forwarding as I've never used your cloud hosting provider before. I'd recommend ngrok which is easy to setup remotely

**Comment by Type-32** [comment]
How do I do that? I thought allowing the 25565 port accessible through the firewall is enough...

**Comment by CheatCod** [comment]
> I can't help you with port forwarding as I've never used your cloud hosting provider before. I'd recommend ngrok which is easy to setup remotely 

^

**Comment by dng-nguyn** [comment]
Late reply but if you're deploying with docker, you need to forward the server's port, usually 25565, from docker to your system in order for the server to communicate online. You should have something like
```yml
version: '3.8'
services:
  lodestone:
    container_name: lodestone
    image: ghcr.io/lodestone-team/lodestone_core
    restart: unless-stopped
    ports:
      - "16662:16662"
      - "25565:25565" #add this
    volumes:
      - lodestone:/home/user/.lodestone

volumes:
  lodestone:
```
