### ISSUE TITLE
Add filter to console window

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/lodestone#311]
# Description

Add a checkbox on the console page to filter for "player message", "system message", "instance output", "instance error"

![image](https://github.com/Lodestone-Team/lodestone/assets/47200772/c88c2610-b045-48d7-8762-77ae5961112e)

# Steps

- [ ] have a design 
- [ ] Frontend implementation

**Comment by Ynng** [comment]
Will this be a good enough solution to #301 ?
