### ISSUE TITLE
Add GitHub Actions step to release dashboard docker image

### ISSUE THREAD

**Issue by stephanrenggli** [Lodestone-Team/lodestone#315]
# Description

Some time ago I added the [Docker image](https://github.com/Lodestone-Team/lodestone/pull/261) required to build the dashboard.
For regular users it would be nice if you added a GitHub Actions step to release a dashboard docker image in addition to the current lodestone docker image.

**Comment by CheatCod** [comment]
This can be done with atom https://github.com/Lodestone-Team/lodestone/wiki/Intro-to-Lodestone-Atom

**Comment by stephanrenggli** [comment]
Could you explain further?
If I understand correctly, Atom is used within lodestone to define and create custom instances (i.e. other games).
How would this replace the dashboard docker image for those of us wanting to self host the entire dashboard?

**Comment by CheatCod** [comment]
Oh oops I replied to the wrong issue sorry
