### ISSUE TITLE
Task page is non-responsive when there is a progression event

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/lodestone#320]
# Description

When there is a progression event being updated by a progression event, the entire macro page will freeze up (cannot click on buttons, switch between table views, etc)

# Steps to reproduce (optional)

Run the following macro

```ts
import { ProgressionHandler } from "https://raw.githubusercontent.com/Lodestone-Team/lodestone-macro-lib/main/events.ts";

const progression = ProgressionHandler.create("title", null);
while (true) {
    // cycle through the animation state
    progression.addProgress(0, "test");
    // sleep for 200ms
    await new Promise((resolve) => setTimeout(resolve, 100));
}
```

Then try to interact with elements on the macro and task page

**Comment by Ynng** [comment]
fixed in ca078b8ae86e50649c506dd6acec2da9aedac619
