### ISSUE TITLE
Lodestone Core should listen on IPv6 by default

### ISSUE THREAD

**Issue by CyanNyan** [Lodestone-Team/lodestone#321]
# Description
Lodestone Core listens 0.0.0.0 by default, which is IPv4 only. It should also listen on IPv6. Not sure if dashboard also need to change to support IPv6.
# Steps to reproduce (optional)
1. Create an environment that support IPv6(for example, [Tailscale VPN](https://tailscale.com/) and enable IPv6 local address)
2. Start Lodestone Core 
3. Connect from dashboard with an IPv6 address
4. Receive connection refused error
![2023-07-29 23 46 10](https://github.com/Lodestone-Team/lodestone/assets/75556638/ea09c3da-def5-4659-98c0-a155adb38409)

**Comment by Ynng** [comment]
I updated frontend to add square brackets [] around ipv6 addresses in eee2696, but core is still missing ipv6 support

**Comment by Ynng** [comment]
Closed by #323
