### ISSUE TITLE
Feature request : Dashboard source code for self-hosting

### ISSUE THREAD

**Issue by Kaipheu** [Lodestone-Team/lodestone#338]
# Description
Hello, can we have access to the [dashboard](https://www.lodestone.cc)'s source code. I already host an lodestone CLI instance on a server and prefer to also host the dashboard on the same server

**Comment by Ynng** [comment]
The source code is in the dashboard folder of this repo
https://github.com/Lodestone-Team/lodestone/tree/main/dashboard

Having lodestone core automatically host the dashboard is planned.

**Comment by Kaipheu** [comment]
Thanks you !
