### ISSUE TITLE
Macro page text is overlapping 

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/lodestone#363]
# Description
<img width="968" alt="image" src="https://github.com/Lodestone-Team/lodestone/assets/47200772/9749c923-780b-418c-ae2f-e39ca6867cbb">

# Steps to reproduce (optional)

**Comment by jhuang38** [comment]
just got around to looking at this, I haven't been able to reproduce this yet. Do you remember if there's anything in particular you did for this?

**Comment by CheatCod** [comment]
Visit dev.lodestone.cc and go to any instance's macro page.

Tested on Chrome Version 120.0.6099.129 (Official Build) (arm64)
