### ISSUE TITLE
Getsockopt

### ISSUE THREAD

**Issue by PikachuLuke5** [Lodestone-Team/lodestone#392]
# Description
Cannot join a server in 1.21. here's the error message: "getsockopt".
![2024-06-18_09 10 13](https://github.com/Lodestone-Team/lodestone/assets/142318212/477161e0-67eb-41e7-a90c-4bd0896dd655)
thats it!
# Steps to reproduce (optional)

**Comment by PikachuLuke5** [comment]
Anyone else having it?

**Comment by CheatCod** [comment]
We can't help with Minecraft server connection issues.
