### ISSUE TITLE
Fix "client side error has occurred" after login in on Firefox

### ISSUE THREAD

**Issue by Ynng** [Lodestone-Team/lodestone#98]

**Comment by thorhs** [comment]
Can confirm, I'm having the same issue.  Both with v0.4.0 .deb and a fresh clone/build.  Attached are the console messages.
[console-export-2023-1-16_20-52-13.txt](https://github.com/Lodestone-Team/lodestone/files/10429412/console-export-2023-1-16_20-52-13.txt)

**Comment by Ynng** [comment]
My current guess is "connecting to a non-secure WebSocket server from a secure origin".

Commenting out all the websocket connections temporarily solves the issue.

In chrome, a warning "Connecting to a non-secure WebSocket server from a secure origin is deprecated" is displayed instead.

**Comment by Ynng** [comment]
This is confirmed. Firefox blocks non-secure websocket even in a mixed-content context, since around Firefox 8.

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications#security_considerations
https://bugzilla.mozilla.org/show_bug.cgi?id=917829

**Comment by Ynng** [comment]
Need to design a warning banner to warn about this issue @Arcslogger
